# Generated by Django 5.1.2 on 2024-11-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_booking_room_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='admin_payment_list', to='hostel.room'),
            preserve_default=False,
        ),
    ]
