# Generated by Django 5.1.2 on 2024-11-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_payment_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='room',
        ),
        migrations.AddField(
            model_name='payment',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
