# Generated by Django 5.1.2 on 2024-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_payment_oprstamp_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Electric_bill', 'Electric_bill'), ('Swiper_bill', 'Swiper_bill'), ('Paper_bill', 'Paper_bill'), ('Internet_bill', 'Internet_bill'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
            ],
        ),
    ]
