# Generated by Django 5.1.2 on 2024-11-20 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.payment'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.payment')),
            ],
        ),
    ]
