# Generated by Django 5.1.2 on 2024-11-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_expenditure_created_at_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
