# Generated by Django 5.1.2 on 2024-12-10 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_expenditure_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_date',
            field=models.OneToOneField(default=0.00024703557312252963, on_delete=django.db.models.deletion.CASCADE, related_name='income_payment_date', to='hostel.payment'),
            preserve_default=False,
        ),
    ]
