# Generated by Django 5.1.2 on 2024-12-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.payment'),
        ),
    ]
