# Generated by Django 5.1.2 on 2024-12-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
