# Generated by Django 5.1.2 on 2024-12-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_alter_income_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_payment_date', to='hostel.payment'),
        ),
    ]
