# Generated by Django 5.1.2 on 2024-12-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_alter_income_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='payment_date',
        ),
    ]
