# Generated by Django 5.1.2 on 2024-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_remove_income_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
